apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-deploy
spec:
  selector:
    matchLabels:
      app: schedule
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: schedule
    spec:
      containers:
        - name: nodejs
          image: '{{ .Values.werf.image.app }}'
          workingDir: /app
          env:
            - name: EKP_PLUGIN_ID
              value: '{{ .Chart.Name }}'
            - name: EKP_PLUGIN_NAME
              value: '.'
            - name: MONGO_HOST
              value: '{{ .Values.mongodb.host }}'
            - name: MONGO_DB_NAME
              value: '{{ .Values.mongodb.db }}'
            - name: MONGO_USER
              value: '{{ .Values.mongodb.user }}'
            - name: MONGO_PASSWORD
              value: '{{ .Values.mongodb.password }}'
            - name: REDIS_HOST
              value: '{{ .Values.redis.host }}'
            - name: REDIS_PASSWORD
              value: '{{ .Values.redis.password }}'
            - name: REDIS_DB
              value: '{{ .Values.redis.db }}'
            - name: NODE_ENV
              value: '{{ .Values.werf.env | default "production" }}'
            - name: PROXY_HOST
              value: '{{ .Values.proxy.host }}'
            - name: PROXY_PORT
              value: '{{ .Values.proxy.port }}'
            - name: PROCESS_TYPE
              value: 'SCHEDULE'
