apiVersion: batch/v1
kind: CronJob
metadata:
  name: schedule
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: schedule
        spec:
          restartPolicy: Never
          containers:
            - name: nodejs
              image: "{{ .Values.werf.image.app }}"
              workingDir: /app
              env:
            - name: MONGO_URI
              value: '{{ .Values.mongodb.uri }}'
            - name: REDIS_HOST
              value: '{{ .Values.redis.host }}'
            - name: REDIS_PASSWORD
              value: '{{ .Values.redis.password }}'
            - name: REDIS_DB
              value: '{{ .Values.redis.db }}'
            - name: NODE_ENV
              value: '{{ .Values.werf.env | default "production" }}'
            - name: PROCESS_TYPE
              value: 'SCHEDULE'
